/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.acme.http.pqc;

import java.io.FileInputStream;
import java.net.URL;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.security.KeyStore;

import javax.net.ssl.KeyManagerFactory;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLException;
import javax.net.ssl.SSLParameters;
import javax.net.ssl.TrustManagerFactory;

import io.quarkus.test.common.http.TestHTTPResource;
import io.vertx.core.net.JdkSSLEngineOptions;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Base class of the PQC tests. Two JDK HTTP clients connect to the server, each offering a single key exchange group
 * through {@link SSLParameters#setNamedGroups(String[])}:
 * <ul>
 * <li>a PQC capable client offering only the hybrid X25519MLKEM768 group</li>
 * <li>a classical client offering only the X25519 group</li>
 * </ul>
 * The certificates in {@code target/certs} are generated by the smallrye-certificate-generator-maven-plugin during the
 * build.
 *
 * Server and clients need a JDK whose TLS implementation supports the hybrid groups (JEP 527). The tests are skipped
 * on other JDKs.
 */
abstract class AbstractPqcTest {

    static final String CLIENT_KEYSTORE = "target/certs/pqc-client-keystore.p12";
    static final String CLIENT_TRUSTSTORE = "target/certs/pqc-client-truststore.p12";
    static final String PASSWORD = "changeit";

    // Evaluated once at class load time
    private static final boolean JDK_PQC_AVAILABLE = JdkSSLEngineOptions.isPqcAvailable();

    @TestHTTPResource(value = "/pqc/secure", tls = true)
    URL url;

    /**
     * Whether the JDK TLS implementation supports post-quantum key exchange. Referenced by name from the
     * {@code @EnabledIf} conditions of the test classes, keep the name in sync.
     */
    static boolean isJdkPqcAvailable() {
        return JDK_PQC_AVAILABLE;
    }

    /**
     * A successful response of a client offering only the hybrid group proves that X25519MLKEM768 was negotiated.
     */
    void assertPqcClientConnects() throws Exception {
        HttpResponse<String> response = send("X25519MLKEM768");
        assertEquals(200, response.statusCode());
        assertTrue(response.body().contains("Post-Quantum Cryptography"));
    }

    void assertClassicalClientConnects() throws Exception {
        assertEquals(200, send("X25519").statusCode());
    }

    /**
     * The server refuses the handshake with a fatal alert. The alert differs by TLS engine: the JDK implementation
     * sends unexpected_message, OpenSSL sends handshake_failure.
     */
    void assertClassicalClientIsRejected() {
        SSLException e = assertThrows(SSLException.class, () -> send("X25519"));
        assertTrue(e.getMessage().contains("Received fatal alert"), "Unexpected failure: " + e);
    }

    private HttpResponse<String> send(String keyExchangeGroup) throws Exception {
        SSLParameters parameters = new SSLParameters();
        parameters.setNamedGroups(new String[] { keyExchangeGroup });
        HttpClient client = HttpClient.newBuilder()
                .sslContext(clientSslContext())
                .sslParameters(parameters)
                .build();
        return client.send(HttpRequest.newBuilder(url.toURI()).GET().build(), HttpResponse.BodyHandlers.ofString());
    }

    private static SSLContext clientSslContext() throws Exception {
        KeyStore keyStore = KeyStore.getInstance("PKCS12");
        try (FileInputStream in = new FileInputStream(CLIENT_KEYSTORE)) {
            keyStore.load(in, PASSWORD.toCharArray());
        }
        KeyStore trustStore = KeyStore.getInstance("PKCS12");
        try (FileInputStream in = new FileInputStream(CLIENT_TRUSTSTORE)) {
            trustStore.load(in, PASSWORD.toCharArray());
        }
        KeyManagerFactory keyManagers = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
        keyManagers.init(keyStore, PASSWORD.toCharArray());
        TrustManagerFactory trustManagers = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
        trustManagers.init(trustStore);
        SSLContext context = SSLContext.getInstance("TLS");
        context.init(keyManagers.getKeyManagers(), trustManagers.getTrustManagers(), null);
        return context;
    }
}
