= Upload a file to an AWS S3 bucket: A Camel Quarkus example
:cq-example-description: An example that shows how to produce and consume messages to an aws2-s3 bucket.

{cq-description}

TIP: Check the https://camel.apache.org/camel-quarkus/latest/first-steps.html[Camel Quarkus User guide] for prerequisites
and other general information.

== Prerequisites

The example application requires an aws2-s3 credentials to access a real service and an existing bucket.

You do need to provide credentials, region and bucket name for your environment (https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/setup.html#setup-credentials[documentation])

* Export Your
https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys[AWS credentials]
(access key ID and secret access key)
* Export your preferred
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-available-regions[AWS region].
* Export name of your bucket

[source,shell]
----
export AWS_ACCESS_KEY=<your-access-key-id>
export AWS_SECRET_KEY=<your-secret-access-key>
export AWS_REGION=eu-central-1
export AWS_BUCKET_NAME=<your-bucket-name>
----

== Start in the Development mode

[source,shell]
----
$ mvn clean compile quarkus:dev
----

The above command compiles the project, starts the application and lets the Quarkus tooling watch for changes in your
workspace. Any modifications in your project will automatically take effect in the running application.

TIP: Please refer to the Development mode section of
https://camel.apache.org/camel-quarkus/latest/first-steps.html#_development_mode[Camel Quarkus User guide] for more details.

=== How the example works

The example is really simple: loads file into your bucket and consumes it.
You should see relevant messages in the log:

[source,shell]
----
Uploaded file with content 'Hello from Camel via aws2-s3!' to s3 bucket xxx
Received body: Hello from Camel via aws2-s3!
----

=== JUnit test

JUnit tests takes advantage of configured credentials (if provided) to use the real Amazon service.
Mocked service is used if credentials are not provided.

=== Package and run the application

Once you are done with developing you may want to package and run the application.

TIP: Find more details about the JVM mode and Native mode in the Package and run section of
https://camel.apache.org/camel-quarkus/latest/first-steps.html#_package_and_run_the_application[Camel Quarkus User guide]

==== JVM mode

[source,shell]
----
$ mvn clean package
$ java -jar target/quarkus-app/quarkus-run.jar
...
[io.quarkus] (main) camel-quarkus-examples-... started in 1.163s.
----

==== Native mode

IMPORTANT: Native mode requires having GraalVM and other tools installed. Please check the Prerequisites section
of https://camel.apache.org/camel-quarkus/latest/first-steps.html#_prerequisites[Camel Quarkus User guide].

To prepare a native executable using GraalVM, run the following command:

[source,shell]
----
$ mvn clean package -Pnative
$ ./target/*-runner
...
[io.quarkus] (main) camel-quarkus-examples-... started in 0.013s.
...
----

== Feedback

Please report bugs and propose improvements via https://github.com/apache/camel-quarkus/issues[GitHub issues of Camel Quarkus] project.