/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.acme.http.pqc.certificates;

import java.io.File;
import java.io.FileOutputStream;
import java.math.BigInteger;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.KeyStore;
import java.security.SecureRandom;
import java.security.cert.Certificate;
import java.security.cert.X509Certificate;
import java.util.Date;

import org.bouncycastle.asn1.x500.X500Name;
import org.bouncycastle.asn1.x509.BasicConstraints;
import org.bouncycastle.asn1.x509.Extension;
import org.bouncycastle.cert.X509v3CertificateBuilder;
import org.bouncycastle.cert.jcajce.JcaX509CertificateConverter;
import org.bouncycastle.cert.jcajce.JcaX509v3CertificateBuilder;
import org.bouncycastle.operator.ContentSigner;
import org.bouncycastle.operator.jcajce.JcaContentSignerBuilder;
import org.jboss.logging.Logger;

/**
 * Utility class for generating and persisting PQC-ready certificates for Java 21.
 * These certificates use RSA keys and are compatible with BouncyCastle JSSE provider
 * which enables PQC hybrid key exchange (X25519MLKEM768) at the TLS layer.
 *
 * <p>
 * Certificates are automatically generated at application startup by
 * {@link SecurityConfiguration} if they don't already exist.
 */
public class CertificateGenerator {

    private static final Logger LOG = Logger.getLogger(CertificateGenerator.class);

    // WARNING: This password is hardcoded for DEMONSTRATION purposes only.
    // In production, use environment variables, secrets management, or secure configuration.
    // NEVER commit real passwords to source control.
    private static final String KEYSTORE_PASSWORD = "changeit";
    private static final String CERT_DIR = "target/certs";

    /**
     * Certificate data holder for keypairs and certificates.
     */
    public static class CertificateData {
        public final KeyPair keyPair;
        public final X509Certificate certificate;

        public CertificateData(KeyPair keyPair, X509Certificate certificate) {
            this.keyPair = keyPair;
            this.certificate = certificate;
        }
    }

    // Cache certificate data to ensure keystores and truststores use the same certificates
    private static CertificateData serverData;
    private static CertificateData clientData;

    public static void generateCertificatesIfNeeded() {
        File certDir = new File("target/certs");
        File serverKeystore = new File(certDir, "server-keystore.p12");

        // Check if certificates already exist (they might have been generated by CertificateTestResource in test mode)
        if (serverKeystore.exists()) {
            LOG.info("Certificates already exist, skipping generation");
            return;
        }

        try {
            LOG.info("Generating fresh PQC-ready keystores...");
            generateServerKeystore();
            generateClientKeystore();
            generateTruststores();
            LOG.info("PQC-ready keystores generated successfully");
        } catch (Exception e) {
            LOG.error("Failed to generate PQC-ready keystores", e);
            throw new RuntimeException("Keystore generation failed", e);
        }
    }

    /**
     * Generates server keystore with RSA certificate.
     */
    public static void generateServerKeystore() throws Exception {
        serverData = generateCertificateData("CN=localhost,O=Camel Quarkus,C=US", true);
        saveKeyStore(Paths.get(CERT_DIR, "server-keystore.p12"), serverData.keyPair, serverData.certificate, "server");
        LOG.info("Server keystore created: " + CERT_DIR + "/server-keystore.p12");
    }

    /**
     * Generates client keystore with RSA certificate.
     */
    public static void generateClientKeystore() throws Exception {
        clientData = generateCertificateData("CN=client,O=Camel Quarkus,C=US", false);
        saveKeyStore(Paths.get(CERT_DIR, "client-keystore.p12"), clientData.keyPair, clientData.certificate, "client");
        LOG.info("Client keystore created: " + CERT_DIR + "/client-keystore.p12");
    }

    /**
     * Generates truststores for both server and client using the cached certificate data.
     * Must be called after generateServerKeystore() and generateClientKeystore().
     */
    public static void generateTruststores() throws Exception {
        if (serverData == null || clientData == null) {
            throw new IllegalStateException("Must call generateServerKeystore() and generateClientKeystore() first");
        }

        saveTrustStore(Paths.get(CERT_DIR, "server-truststore.p12"), clientData.certificate, "client-ca");
        LOG.info("Server truststore created: " + CERT_DIR + "/server-truststore.p12");

        saveTrustStore(Paths.get(CERT_DIR, "client-truststore.p12"), serverData.certificate, "server-ca");
        LOG.info("Client truststore created: " + CERT_DIR + "/client-truststore.p12");
    }

    /**
     * Generates a certificate with RSA keypair.
     *
     * @param  dn   The DN for the certificate subject
     * @param  isCA Whether this is a CA certificate
     * @return      CertificateData containing keypair and certificate
     */
    private static CertificateData generateCertificateData(String dn, boolean isCA) throws Exception {
        KeyPair keyPair = generateKeyPair();
        X509Certificate certificate = generateCertificate(keyPair, dn, isCA);
        return new CertificateData(keyPair, certificate);
    }

    private static KeyPair generateKeyPair() throws Exception {
        KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance("RSA");
        // Use 4096-bit RSA for future-proofing, consistent with PQC security goals
        keyPairGenerator.initialize(4096, new SecureRandom());
        return keyPairGenerator.generateKeyPair();
    }

    private static X509Certificate generateCertificate(KeyPair keyPair, String dn, boolean isCA) throws Exception {
        long now = System.currentTimeMillis();
        Date notBefore = new Date(now);
        // Valid for 3 years for development convenience
        Date notAfter = new Date(now + 1095L * 24 * 60 * 60 * 1000);

        X500Name dnName = new X500Name(dn);
        // Use SecureRandom for better entropy in serial numbers
        BigInteger serial = new BigInteger(64, new SecureRandom());

        X509v3CertificateBuilder certBuilder = new JcaX509v3CertificateBuilder(
                dnName,
                serial,
                notBefore,
                notAfter,
                dnName,
                keyPair.getPublic());

        certBuilder.addExtension(Extension.basicConstraints, true, new BasicConstraints(isCA));

        // Use default SUN provider for RSA signing - no need for BC provider
        ContentSigner signer = new JcaContentSignerBuilder("SHA256WithRSA")
                .build(keyPair.getPrivate());

        return new JcaX509CertificateConverter()
                .getCertificate(certBuilder.build(signer));
    }

    private static void saveKeyStore(Path path, KeyPair keyPair, X509Certificate cert, String alias) throws Exception {
        Path dirPath = path.getParent();
        if (!Files.exists(dirPath)) {
            Files.createDirectories(dirPath);
            LOG.info("Created directory: " + dirPath);
        }

        // Use SUN provider for PKCS12 to ensure compatibility with curl/OpenSSL
        KeyStore keyStore = KeyStore.getInstance("PKCS12");
        keyStore.load(null, null);
        keyStore.setKeyEntry(alias, keyPair.getPrivate(), KEYSTORE_PASSWORD.toCharArray(),
                new Certificate[] { cert });

        try (FileOutputStream fos = new FileOutputStream(path.toFile())) {
            keyStore.store(fos, KEYSTORE_PASSWORD.toCharArray());
        }
    }

    private static void saveTrustStore(Path path, X509Certificate cert, String alias) throws Exception {
        Path dirPath = path.getParent();
        if (!Files.exists(dirPath)) {
            Files.createDirectories(dirPath);
            LOG.info("Created directory: " + dirPath);
        }

        // Use SUN provider for PKCS12 to ensure compatibility with curl/OpenSSL
        KeyStore trustStore = KeyStore.getInstance("PKCS12");
        trustStore.load(null, null);
        trustStore.setCertificateEntry(alias, cert);

        try (FileOutputStream fos = new FileOutputStream(path.toFile())) {
            trustStore.store(fos, KEYSTORE_PASSWORD.toCharArray());
        }
    }

    public static void main(String[] args) {
        try {
            LOG.info("Generating PQC-ready certificates...");
            generateServerKeystore();
            generateClientKeystore();
            generateTruststores();
            LOG.info("PQC-ready certificates generated successfully");
        } catch (Exception e) {
            LOG.error("Failed to generate certificates", e);
            System.exit(1);
        }
    }
}
