= Artemis to ElasticSearch
:cq-example-description: An example that shows how the message is consumed from the Apache Artemis broker using MQTT protocol, transformed and loaded into ElasticSearch

{cq-description}

This example shows how to connect ActiveMQ Broker to Elasticsearch service, create index and send data to it.

TIP: Check the https://camel.apache.org/camel-quarkus/latest/first-steps.html[Camel Quarkus User guide] for prerequisites
and other general information.

== Prerequisites:

In order to send a message from Artemis Broker to Elasticsearch you need to start two services:

1) ActiveMQ Artemis - message broker that is connected to a paho client.

2) Elasticsearch - database that stores your data.

You can also use podman instead of docker for all the steps below.


== Create network for Elasticsearch:

[source,shell]
----
docker network create elastic
----

== Run the containers:

=== Run the Artemis container:

[source,shell]
----
docker run -d --rm -e AMQ_EXTRA_ARGS="--relax-jolokia" -e AMQ_USER=admin -e AMQ_PASSWORD=admin -p 61616:61616 -p 8161:8161 -p 1883:1883 --name artemis quay.io/artemiscloud/activemq-artemis-broker:1.0.26
----

Now you can access Artemis on localhost:8161

=== Run the Elasticsearch container:

[source,shell]
----
docker run -d --rm --name elasticsearch --net elastic -p 9200:9200 -p 9300:9300 -it -m 4GB -e "discovery.type=single-node" -e "xpack.security.enabled=false" --name elasticsearch docker.elastic.co/elasticsearch/elasticsearch:8.12.0
----

Now you can access Elasticsearch on localhost:9200

== Start the quarkus application:

=== In jvm mode:

[source,shell]
----
mvn clean package
----

[source,shell]
----
java -Delasticsearch.host=localhost:9200 -jar target/quarkus-app/quarkus-run.jar
----

=== In development mode:

[source, shell]
----
mvn clean verify quarkus:dev
----

== Send and retrieve messages:

=== Send from Artemis Broker:
----
docker exec -it artemis broker/bin/artemis producer --destination topic://devices --message-count 10 --message="Hello world"
----


=== Retrieve from Elasticsearch:

----
curl -X GET "localhost:9200/devices/_msearch?pretty" -H 'Content-Type: application/json' -d'
{ }
{"index": "devices"}
{"query" : {"match_all" : {}}}
'
----

== Stop the containers:

----
docker stop kibana
docker stop elasticsearch
docker stop artemis
----
