## ---------------------------------------------------------------------------
## Licensed to the Apache Software Foundation (ASF) under one or more
## contributor license agreements.  See the NOTICE file distributed with
## this work for additional information regarding copyright ownership.
## The ASF licenses this file to You under the Apache License, Version 2.0
## (the "License"); you may not use this file except in compliance with
## the License.  You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ---------------------------------------------------------------------------
quarkus.banner.enabled = false
quarkus.default-locale=en_US

# Configure Quarkus LangChain4j that handles interactions with the Large Language Model
# Adjust as per where your Ollama instance is running
quarkus.langchain4j.ollama.base-url=http://localhost:11434
quarkus.langchain4j.ollama.timeout=3m
# The chat model to use
quarkus.langchain4j.ollama.chat-model.model-id=granite4.1:3b
quarkus.langchain4j.ollama.chat-model.temperature=0
quarkus.langchain4j.ollama.chat-model.top-k=1
quarkus.langchain4j.ollama.chat-model.top-p=0.1
# Ollama is run by you rather than by Dev Services
quarkus.langchain4j.ollama.devservices.enabled=false
# Uncomment lines below to log Ollama client requests and responses
#quarkus.langchain4j.ollama.log-requests=true
#quarkus.langchain4j.ollama.log-responses=true
