#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Camel Quarkus CI

on:
  push:
    branches:
      - main
      - camel-quarkus-main
      - "[0-9]+.[0-9]+.x"
    paths-ignore:
      - '**.adoc'
      - '**.md'
      - 'Jenkinsfile'
      - 'KEYS'
      - 'LICENSE.txt'
      - 'NOTICE.txt'
  pull_request:
    branches:
      - main
      - camel-quarkus-main
      - "[0-9]+.[0-9]+.x"
    paths-ignore:
      - '**.adoc'
      - '**.md'
      - 'Jenkinsfile'
      - 'KEYS'
      - 'LICENSE.txt'
      - 'NOTICE.txt'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  LANG: en_US.UTF-8
  MAVEN_OPTS: -Xmx4000m
  MAVEN_ARGS: -V -ntp -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -e
  TESTCONTAINERS_RYUK_DISABLED: true

jobs:
  initial-mvn-install:
    if: github.repository == 'apache/camel-quarkus-examples'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-itest-matrix.outputs.matrix }}
      modules: ${{ steps.set-itest-matrix.outputs.modules }}
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Checkout Camel Quarkus
        id: build-camel-quarkus
        if: github.ref == 'refs/heads/camel-quarkus-main' || github.base_ref == 'camel-quarkus-main'
        run: |
          git clone --depth 1 --branch main https://github.com/apache/camel-quarkus.git ${{ runner.temp }}/camel-quarkus
          cd ${{ runner.temp }}/camel-quarkus
          echo "Current Camel Quarkus commit:" $(git rev-parse HEAD)
          JIRA_VERSION=$(./mvnw help:evaluate -Dexpression=jira-rest-client.version -q -DforceStdout -N)
          echo "atlassian-version=${JIRA_VERSION}" >> $GITHUB_OUTPUT
      - name: Restore Atlassian Maven Cache
        if: github.ref == 'refs/heads/camel-quarkus-main' || github.base_ref == 'camel-quarkus-main'
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.m2/repository/com/atlassian
            ~/.m2/repository/io/atlassian
          key: atlassian-maven-${{ steps.build-camel-quarkus.outputs.atlassian-version }}
      - name: Build Camel Quarkus
        if: github.ref == 'refs/heads/camel-quarkus-main' || github.base_ref == 'camel-quarkus-main'
        run: |
          cd ${{ runner.temp }}/camel-quarkus
          ./mvnw ${MAVEN_ARGS} clean install -Dquickly -T1C
      - name: Save Atlassian Maven Cache
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        if: github.ref == 'refs/heads/camel-quarkus-main' || github.base_ref == 'camel-quarkus-main'
        with:
          path: |
            ~/.m2/repository/com/atlassian
            ~/.m2/repository/io/atlassian
          key: atlassian-maven-${{ steps.build-camel-quarkus.outputs.atlassian-version }}
      - name: mvn cq:examples-check-platform
        run: mvn org.l2x6.cq:cq-maven-plugin:2.10.0:examples-check-platform
      - name: mvn ${MAVEN_ARGS} license:check formatter:validate impsort:check
        run: |
          ./mvnw ${MAVEN_ARGS} \
            license:check \
            net.revelc.code.formatter:formatter-maven-plugin:validate \
            net.revelc.code:impsort-maven-plugin:check
      - name: Fetch base branch for Scalpel
        if: github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'ci/disable-incremental')
        run: git fetch --unshallow origin ${{ github.base_ref }}
      - name: Build Camel Quarkus Examples
        run: |
          ./mvnw ${MAVEN_ARGS} clean install -DskipTests -Dquarkus.build.skip \
            -Dscalpel.enabled=true \
            -Dscalpel.mode=report \
            -Dscalpel.reportFile=${{ runner.temp }}/scalpel-report.json
      - name: Fail if there are uncommitted changes
        shell: bash
        run: |
          [[ -z $(git status --porcelain) ]] || { echo 'There are uncommitted changes'; git status; exit 1; }
      - name: Setup Integration Test Matrix
        id: set-itest-matrix
        run: bash .github/generate-test-matrix.sh '${{ runner.temp }}/scalpel-report.json' >> $GITHUB_OUTPUT
      - name: Tar Maven Repo
        shell: bash
        run: |
          tar -I 'zstd -T0' -cf ${{ runner.temp }}/maven-repo.tar.zst -C ~ .m2/repository
      - name: Persist Maven Repo
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: maven-repo
          path: ${{ runner.temp }}/maven-repo.tar.zst
          retention-days: 1

  integration-tests:
    name: Integration Tests - ${{matrix.name}}
    needs: initial-mvn-install
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.initial-mvn-install.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up JDK 17
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Download Maven Repo
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: maven-repo
          path: ..
      - name: Extract Maven Repo
        shell: bash
        run: |
          tar -I 'zstd -d' -xf ../maven-repo.tar.zst -C ~
      - name: Integration Tests
        env:
          TEST_MODULES: ${{matrix.tests}}
        shell: '/usr/bin/bash {0}'
        run: |
          BUILD_FAILURES=()

          for MODULE in ${TEST_MODULES//,/ }; do
            cd ${MODULE}

            ../mvnw ${MAVEN_ARGS} clean verify \
              -Dformatter.skip -Dimpsort.skip \
              -Dquarkus.native.builder-image.pull=missing \
              -Pnative,docker,ci

            if [[ $? -ne 0 ]]; then
              BUILD_FAILURES[${#BUILD_FAILURES[@]}]=${MODULE}
            fi

            cd -
          done

          if [[ ${#BUILD_FAILURES[@]} -gt 0 ]]; then
            echo -e "\nBuild errors were encountred in the following projects:\n"
            for FAILURE in ${BUILD_FAILURES[@]}; do
                echo "* ${FAILURE}"
            done
            echo -e "\nCheck build logs for further information."
            exit 1
          fi
      - name: Fail if there are uncommitted changes
        shell: bash
        run: |
          [[ -z $(git status --porcelain) ]] || { echo 'There are uncommitted changes'; git status; exit 1; }

  integration-tests-alternative-jdk:
    name: Integration Tests JDK - ${{ matrix.jdk }}
    needs: initial-mvn-install
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: ['21']
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up JDK {{ matrix.jdk }}
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}
      - name: Download Maven Repo
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: maven-repo
          path: ..
      - name: Extract Maven Repo
        shell: bash
        run: |
          tar -I 'zstd -d' -xf ../maven-repo.tar.zst -C ~
      - name: Integration Tests
        shell: bash
        run: |
          ./mvnw ${MAVEN_ARGS} clean test \
            -pl ${{ needs.initial-mvn-install.outputs.modules }}
      - name: Fail if there are uncommitted changes
        shell: bash
        run: |
          [[ -z $(git status --porcelain) ]] || { echo 'There are uncommitted changes'; git status; exit 1; }

  integration-tests-alternative-platform:
    name: Integration Tests Alternative Platform - ${{matrix.os}}
    needs: initial-mvn-install
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up JDK 17
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Download Maven Repo
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: maven-repo
          path: ..
      - name: Extract Maven Repo
        shell: bash
        run: |
          tar -I 'zstd -d' -xf ../maven-repo.tar.zst -C ~
      - name: Integration Tests
        shell: bash
        run: |
          ./mvnw ${MAVEN_ARGS} -Dskip-testcontainers-tests clean test \
            -pl ${{ needs.initial-mvn-install.outputs.modules }}
      - name: Fail if there are uncommitted changes
        shell: bash
        run: |
          [[ -z $(git status --porcelain) ]] || { echo 'There are uncommitted changes'; git status; exit 1; }
